name: CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Build with Gradle
        run: |
          ./gradlew clean asciidoctorPdf jreleaserRelease
          ls -la build/docs/asciidocPdf/
          ./gradlew jreleaserRelease
        env:
          BUILD_NUMBER: ${{ env.GITHUB_RUN_NUMBER }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.JRELEASER_GITHUB_TOKEN }}
      # - name: Push docker image
      #   run: |
      #     export CI_JOB_TIMESTAMP=$(date +%Y%m%dT%H%M%S)
      #     docker images
      #     ./gradlew web-service:pushDockerImages
      #   env:
      #     DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      #     DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      