name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Build with Gradle
        run: |
          ./gradlew clean asciidoctorPdf
          ls -la build/docs/asciidocPdf/
        env:
          BUILD_NUMBER: ${{ env.GITHUB_RUN_NUMBER }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.JRELEASER_GITHUB_TOKEN }}
      - name: Release 
        run: |
          ls -la build/docs/asciidocPdf/
          ./gradlew jreleaserRelease -i -d
        env:
          BUILD_NUMBER: ${{ env.GITHUB_RUN_NUMBER }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.JRELEASER_GITHUB_TOKEN }}
